### ISSUE TITLE
Included tailwind css doesn't match tailwind config

### ISSUE THREAD

**Issue by padders** [statamic/starter-kit-cool-writings#3]
Hi Guys, 

Just trying out the starter, and found that the tailwind class text-center wasn't there. On a recompile after running npm install, and then npm run prod it was in tailwind.css correctly. Looks like the included css might be out of line with the config files?

Cheers
Paul

**Comment by jackmcdade** [comment]
Paul, that's because the default/precompiled assets used [PurgeCSS](https://purgecss.com/) to remove unused classes. Without it, as you can now see, the Tailwind generated css file is a couple hundred kb. 

I'll make a note of this in the README as you're the second person so encounter it. Thanks for the nudge!

**Comment by padders** [comment]
Thanks Jack, 

I was just coming to the same conclusion as I was struggling to get the height components in too. Need to figure out PurgeCss and my template files to make sure the relevant css is included

Cheers :)

**Comment by jackmcdade** [comment]
No prob! It's only run when you do `npm run production`. If you want to cut it out entirely, just remove the following lines:

https://github.com/statamic/starter-kit-cool-writings/blob/master/webpack.mix.js#L24-L26
