### ISSUE TITLE
Recompiling CSS does not work out of the box

### ISSUE THREAD

**Issue by vladstanca** [statamic/starter-kit-cool-writings#4]
The ```resources/css/site.css``` file seems to be a sass file. Recompiling css with ```npm run dev``` generates a file that does not include the nested properties.

To make thinks simpler, either site.css should be CSS or a webpack.mix.js should be updated to process sass in order to avoid confusion.

Tailwind docs recommend not using SASS, but if SASS is used, there's also a bug affecting laravel mix that should be considered. https://tailwindcss.com/docs/installation/#laravel-mix

**Comment by jackmcdade** [comment]
You're totally right. It's not actually SASS, it's just nested CSS using the `postcss-nested` plugin. It was originally included explicitly but got removed in [PR 1](https://github.com/statamic/starter-kit-cool-writings/pull/1) because it was supposed to be included along with `postcss-preset-env`. I couldn't get it to work so I added it back.

Thanks for noticing!
